service: tagging-handler

provider:
  name: aws
  runtime: nodejs12.x

functions:
  tag:
    handler: handler.tag
    role: arn:aws:iam::486660723778:role/lambda-sqs-rekognition
    events:
      - sns: arn:aws:sns:us-east-1:486660723778:s3-nanoservice-images-put-topic