service: http-handler
plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  apigwBinary:
    types:
      - "image/jpeg"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  upload:
    handler: handler.upload
    role: arn:aws:iam::486660723778:role/lambda-http-handler
    events:
      - http:
          path: images
          method: post
